### ISSUE TITLE
Documentation for Filtering / Rules? (how to filter with wildcard? or filter by existence of custom journal field?)

### ISSUE THREAD

**Issue by riwoodward** [mosquito/cysystemd#66]
I've just discovered `cysystemd` - great package, thanks for all your work on it.

However, I'm having trouble with the `Rules` syntax and application of these for efficient filtering of journald entries. Is there any documentation for this please? Or more examples - e.g. projects you know that use `cysystemd`?

Specifically, my two questions are:

1. Using `journalctl` it's possible to use wildcards when searrching for journal fields. How can I do this with `cysystemd` please? For example, the example in the README is:
```python
from cysystemd.reader import JournalReader, JournalOpenMode, Rule

rules = (
  Rule("SYSLOG_IDENTIFIER", "CRON") &
  Rule("_SYSTEMD_UNIT", "crond.service") |
  Rule("_SYSTEMD_UNIT", "cron.service")
)

cron_reader = JournalReader()
cron_reader.open(JournalOpenMode.SYSTEM)
cron_reader.seek_head()
cron_reader.add_filter(rules)
```

But if I try to use a wildcard, e.g. `Rule("SYSLOG_IDENTIFIER", "CR*") ` I get no matches.

2. Is it possible to add a filter that matches events which simply contain some custom journal field, irrelevant of its contents. For example, say I write journal entries like this:
```python
from cysystemd import journal
journal.send(
    message="Hello",
    priority=journal.Priority.INFO,
    some_field='some value',
)
```
How do I use the `JournalReader()` to filter events which contain the `some_field` key, irrelevant of the value assigned to that field?

Thank you.

**Comment by mosquito** [comment]
Thank you for your kind words and for using `cysystemd`! I'm glad to hear that you're finding the package useful.

Wildcard matching isn't natively supported by `cysystemd`'s `Rule` syntax, but there are workarounds to achieve similar functionality. As for filtering based on the presence of a custom field, you need to adapt the filtering to iterate through entries manually.

`cysystemd` doesn't directly support wildcards in the `Rule` API as `journalctl` does in its query syntax. This is because `cysystemd` uses the underlying [`sd_journal_add_match`](https://www.freedesktop.org/software/systemd/man/latest/sd_journal_add_match.html) C-library call, which doesn't interpret wildcards like shell globbing.

To achieve similar functionality, you need to fetch the entries and then filter them programmatically in Python. For example:

```python
import fnmatch
from cysystemd.reader import JournalReader, JournalOpenMode, Rule

cron_reader = JournalReader()
cron_reader.open(JournalOpenMode.SYSTEM)
cron_reader.seek_head()

while cron_reader.get_next():
    entry = cron_reader.get_entry()
    if fnmatch.fnmatch(entry.get("SYSLOG_IDENTIFIER", ""), "CR*"):
        print(entry)
```

In this case, `fnmatch.fnmatch()` will allow you to apply a wildcard-like filter after retrieving each journal entry.

**Comment by riwoodward** [comment]
Thanks for the quick reply. That makes sense and should work.

I just wondered if there was a Rule-based approach that may be more efficient than iterating over all entries.

Thanks!
